version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - blog-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql  # Reference your init.sql here
    networks:
      - blog-network

  blog-application:
    build: ./blog-app
    container_name: blog-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - blog-network

networks:
  blog-network:

volumes:
  postgres-data:
